### ISSUE TITLE
OpenVpn (mbedtls) fails on WDR4900 on Hedy1.0.x

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#538]
On 28.03.2018 15:06 Erik reported on the Berlin mailing list (https://lists.berlin.freifunk.net/pipermail/berlin/2018-March/037457.html) that the new Firmware is not woring on the WDR4900.  I can verify this problem.

I used the same setup on a WDR4900 and a WDR4300. Only with the WDR4900 do I have this problem.

```
Thu Mar 29 01:15:30 2018 daemon.notice openvpn(ffuplink)[3520]: OpenVPN 2.4.4 powerpc-openwrt-linux-gnu [SSL (mbed TLS)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
Thu Mar 29 01:15:30 2018 daemon.notice openvpn(ffuplink)[3520]: library versions: mbed TLS 2.6.0, LZO 2.10
Thu Mar 29 01:15:30 2018 daemon.warn openvpn(ffuplink)[3520]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Thu Mar 29 01:15:30 2018 kern.info kernel: [  200.487285] openvpn[3520]: unhandled signal 4 at b7b6ba40 nip b7b6ba40 lr b7b59cfc code 30001
```

**Comment by SvenRoederer** [comment]
I assume the WDR4900 is a different arch than WDR3600, right?

Can you test with the recent master-build, as it's using mbedtls 2.7.0 (Hedy 1.0.0 has 2.6.0)

**Comment by pmelange** [comment]
It woks with the master branch

**Comment by SvenRoederer** [comment]
so options are:
1. postpone till next major relase (based on OpenWrt 18.04+)
1. somebody will upgrade Hedy (lede-17.x) to mebdtls 2.7.0
1. somebody fixes Mbedtls 2.6.0 for lede-17.x
1. we switch to openvpn-openssl in Hedy-1.0.1 (as using openvpn-mbedtls will not make the image fit into 4MB, as intended)

! vote for 1. or 4.

**Comment by torte71** [comment]
I'd say: 4. - It will circumvent the 1024bit key problem for BBB-VPN as well (and VPN03, if the transition will take longer, than expected).
The chances for getting a usable 4MB+Tunnel image are quite low - if someone gets that done, we can still use mbedtls for those images.

**Comment by pmelange** [comment]
1. I would call "fixed upstream"
4. Makes sense when the goal is to have a single OpenVPN based image which can connect to a wide range of VPN's including the bbb-vpn, icvpn, tunnel-berin, vpn03, and any other VPN services (such as hide.me).

I vote for 4.

**Comment by bobster-galore** [comment]
I vote for 4.

**Comment by SvenRoederer** [comment]
since https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=f609913b5c60f7c65c462730993cd1c752083fd6 OpenWrt Lede-17.01 branch is also on v2.7.0 of mbedtls.
This should make Hedy-1.0.1 (including current alpha-builds) work.

@pmelange can you test?

**Comment by pmelange** [comment]
I cannot test this with the latest Hedy-1.0.1.  

```
The uploaded image file does not contain a supported format. Make sure that you choose the generic image format for your platform
```

I am absolutely sure I have the right platform.

hedy-1.0.1-alpha-6f4686a-tl-wdr4900-v1-sysupgrade.bin

**Comment by pmelange** [comment]
Update...  I also could not flash Hedy-1.0.0 via the luci interface.  Doing a sysupgrade -F...

And after doing the force upgrade, I am able to flash the hedy-1.0.1-alpha-6f4686a-tl-wdr4900-v1-sysupgrade.bin image without any warnings...

**Comment by pmelange** [comment]
Now I can verify that Hedy-1.0.1 alpha 6f4686a does _not_ work

```
Sun Apr  1 20:29:30 2018 daemon.notice openvpn(ffuplink)[4368]: OpenVPN 2.4.4 powerpc-openwrt-linux-gnu [SSL (mbed TLS)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
Sun Apr  1 20:29:30 2018 daemon.notice openvpn(ffuplink)[4368]: library versions: mbed TLS 2.7.0, LZO 2.10
Sun Apr  1 20:29:30 2018 daemon.warn openvpn(ffuplink)[4368]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Sun Apr  1 20:29:30 2018 kern.info kernel: [   71.222434] openvpn[4368]: unhandled signal 4 at b78012fc nip b78012fc lr b77ed58c code 30001
```

**Comment by SvenRoederer** [comment]
for LEDE-17.01 mbetls has been updated to v2.7.x, so in the Hedy-1.0.2 builds this issue should have been solved.
Please recheck

**Comment by SvenRoederer** [comment]
So probably someone should trigger a build or build locally ...

**Comment by SvenRoederer** [comment]
I recently updated the Hedy-1.0.2 branch to Lede-17.01-6, so there is a build avail for testing

**Comment by pmelange** [comment]
I had to force the upgrade again...  Anyhow, I'm still getting the same errors as above with 1.0.2.

**Comment by pmelange** [comment]
I have tested again with the lastest from the Hedy-1.0.2 branch.  This problem is still present.

**Comment by SvenRoederer** [comment]
so we should implement option 4 (switch to openvpn-openssl) for Hedy-1.0.2.
For v1.1.x it should be fixed by upsteam updates of OpenVpn and mbedTLS

**Comment by pmelange** [comment]
I think this is a good solution

**Comment by pmelange** [comment]
Option 4, accomplished with commit 6a3f511, works as expected.

Closing issue

**Comment by pmelange** [comment]
I can confirm that openvpn-mbedtls works on firmware based on 18.06

**Comment by SvenRoederer** [comment]
@pmelange you already mentioned this in https://github.com/freifunk-berlin/firmware/issues/538#issuecomment-377075619
